INSERT INTO products (title, price) VALUES ('Samsung', 850),
                                           ('IPhone', 1200),
                                           ('IPhone X', 1100),
                                           ('IPhone V', 900),
                                           ('IPhone S', 990),
                                           ('IPhone IX', 1230),
                                           ('Samsung GalaxyLite', 850),
                                           ('Samsung Galaxy', 1350),
                                           ('Samsung A100', 850),
                                           ('Samsung', 1150),
                                           ('BlackBarry', 1150),
                                           ('BlackBarry 3', 2597),
                                           ('BlackBarry 3', 2597),
                                           ('BlackBarry 1', 1597),
                                           ('BlackBarry 1', 1597),
                                           ('Xaomy ReadMe', 450),
                                           ('Xaomy Note', 600),
                                           ('Xaomy Note4', 850),
                                           ('Xaomy', 550),
                                           ('Xaomy', 550);
