INSERT INTO products (title, price) VALUES ('XLR 125', 2750);
INSERT INTO products (title, price) VALUES ('XLR 125', 2850);
INSERT INTO products (title, price) VALUES ('XLR 125', 2900);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 6 GREEN', 700);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 6 GREEN', 700);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 6 GREEN', 700);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 6 GREEN', 700);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 6 GREEN', 700);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 YELLOW', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 YELLOW', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 YELLOW', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 WHITE', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 WHITE', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 5 WHITE', 800);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 4 DARK', 1200);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 4 DARK', 1200);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 4 DARK', 1200);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 3 BLUE', 1650);
INSERT INTO products (title, price) VALUES ('CANNONDALE TRAIL 3 RED', 1650);
INSERT INTO products (title, price) VALUES ('PRIDE RED', 650);
INSERT INTO products (title, price) VALUES ('PRIDE BLUE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE BLUE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE BLUE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE BLUE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE WHITE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE WHITE', 650);
INSERT INTO products (title, price) VALUES ('PRIDE GREEN', 650);
INSERT INTO products (title, price) VALUES ('PRIDE GREEN', 650);
INSERT INTO products (title, price) VALUES ('PRIDE GREEN', 650);
INSERT INTO products (title, price) VALUES ('PRIDE GREEN', 650);
INSERT INTO products (title, price) VALUES ('F 650 FUNDURO', 3450);
INSERT INTO products (title, price) VALUES ('F 650 FUNDURO', 3250);
INSERT INTO products (title, price) VALUES ('F 650 FUNDURO', 3650);
INSERT INTO products (title, price) VALUES ('F 650 FUNDURO', 3400);
INSERT INTO products (title, price) VALUES ('BMW G650', 12750);
INSERT INTO products (title, price) VALUES ('BMW G650', 12750);
INSERT INTO products (title, price) VALUES ('BMW G650', 12750);
INSERT INTO products (title, price) VALUES ('BMW G650', 12750);
INSERT INTO products (title, price) VALUES ('BMW G650', 12750);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW F650GS', 4250);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('BMW G1250', 19750);
INSERT INTO products (title, price) VALUES ('PEGASO 650', 3350);
INSERT INTO products (title, price) VALUES ('PEGASO 650', 3350);
INSERT INTO products (title, price) VALUES ('PEGASO 650', 3350);
INSERT INTO products (title, price) VALUES ('PEGASO 650', 3350);
INSERT INTO products (title, price) VALUES ('PEGASO 650', 3350);
INSERT INTO products (title, price) VALUES ('FREEWIND 650', 3700);
INSERT INTO products (title, price) VALUES ('FREEWIND 650', 3700);
INSERT INTO products (title, price) VALUES ('FREEWIND 650', 3700);
INSERT INTO products (title, price) VALUES ('FREEWIND 650', 3700);
INSERT INTO products (title, price) VALUES ('FREEWIND 650', 3700);
INSERT INTO products (title, price) VALUES ('CAPONORD 1000', 5950);
INSERT INTO products (title, price) VALUES ('CAPONORD 1000', 5950);
INSERT INTO products (title, price) VALUES ('CAPONORD 1000', 5950);

--rollback DELETE FROM products;
