INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 567);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 456);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 760);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 870);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 424);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 954);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 642);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 822);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 543);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 398);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 656);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 872);
INSERT INTO products (title, price) VALUES ('Samsung Galaxy Prime', 934);
INSERT INTO products (title, price) VALUES ('LG G-520', 234);
INSERT INTO products (title, price) VALUES ('LG G-520', 545);
INSERT INTO products (title, price) VALUES ('LG G-520', 233);
INSERT INTO products (title, price) VALUES ('LG G-520', 875);
INSERT INTO products (title, price) VALUES ('LG G-520', 343);
INSERT INTO products (title, price) VALUES ('LG G-520', 232);
INSERT INTO products (title, price) VALUES ('LG G-520', 323);
INSERT INTO products (title, price) VALUES ('LG G-520', 864);
INSERT INTO products (title, price) VALUES ('LG G-520', 434);
INSERT INTO products (title, price) VALUES ('LG G-520', 745);
INSERT INTO products (title, price) VALUES ('LG G-520', 232);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 954);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 432);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 232);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 767);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 543);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 956);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 834);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 235);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 752);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 454);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 676);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 983);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 232);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 124);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 653);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 875);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 423);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 234);
INSERT INTO products (title, price) VALUES ('XIAOMI 10PRO', 765);

--rollback DELETE FROM products;
