--liquibase formatted sql
--changeset <glebshevchenko>:<create-products-table>

INSERT INTO products (title, price) VALUES ('iPhone 11', 550);
INSERT INTO products (title, price) VALUES ('iPhone 11', 560);
INSERT INTO products (title, price) VALUES ('iPhone 11', 570);
INSERT INTO products (title, price) VALUES ('iPhone 11', 580);
INSERT INTO products (title, price) VALUES ('iPhone 11', 590);
INSERT INTO products (title, price) VALUES ('iPhone 11', 600);
INSERT INTO products (title, price) VALUES ('iPhone 11', 610);
INSERT INTO products (title, price) VALUES ('iPhone 11', 620);
INSERT INTO products (title, price) VALUES ('iPhone 11', 630);
INSERT INTO products (title, price) VALUES ('iPhone 11', 640);
INSERT INTO products (title, price) VALUES ('iPhone 11', 650);
INSERT INTO products (title, price) VALUES ('iPhone 11', 660);
INSERT INTO products (title, price) VALUES ('iPhone 11', 670);
INSERT INTO products (title, price) VALUES ('iPhone 11', 680);
INSERT INTO products (title, price) VALUES ('iPhone 11', 690);
INSERT INTO products (title, price) VALUES ('iPhone 11', 700);
INSERT INTO products (title, price) VALUES ('iPhone 11', 710);
INSERT INTO products (title, price) VALUES ('iPhone 11', 720);
INSERT INTO products (title, price) VALUES ('iPhone 11', 730);
INSERT INTO products (title, price) VALUES ('iPhone 11', 740);
INSERT INTO products (title, price) VALUES ('iPhone 11', 750);
INSERT INTO products (title, price) VALUES ('iPhone 11', 760);
INSERT INTO products (title, price) VALUES ('iPhone 11', 770);
INSERT INTO products (title, price) VALUES ('iPhone 12', 780);
INSERT INTO products (title, price) VALUES ('iPhone 12', 790);
INSERT INTO products (title, price) VALUES ('iPhone 12', 800);
INSERT INTO products (title, price) VALUES ('iPhone 12', 810);
INSERT INTO products (title, price) VALUES ('iPhone 12', 820);
INSERT INTO products (title, price) VALUES ('iPhone 12', 830);
INSERT INTO products (title, price) VALUES ('iPhone 12', 840);
INSERT INTO products (title, price) VALUES ('iPhone 12', 850);
INSERT INTO products (title, price) VALUES ('iPhone 12', 860);
INSERT INTO products (title, price) VALUES ('iPhone 12', 870);
INSERT INTO products (title, price) VALUES ('iPhone 12', 880);
INSERT INTO products (title, price) VALUES ('iPhone 12', 890);
INSERT INTO products (title, price) VALUES ('iPhone 12', 900);
INSERT INTO products (title, price) VALUES ('Samsung G22', 910);
INSERT INTO products (title, price) VALUES ('Samsung G22', 920);
INSERT INTO products (title, price) VALUES ('Samsung G22', 930);
INSERT INTO products (title, price) VALUES ('Samsung G22', 940);
INSERT INTO products (title, price) VALUES ('Samsung G22', 950);
INSERT INTO products (title, price) VALUES ('Samsung G22', 960);
INSERT INTO products (title, price) VALUES ('Samsung G22', 970);
INSERT INTO products (title, price) VALUES ('Samsung G22', 980);
INSERT INTO products (title, price) VALUES ('Samsung G22', 990);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1000);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1100);
INSERT INTO products (title, price) VALUES ('Samsung G23', 1150);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1200);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1250);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1300);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1350);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1400);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1450);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1500);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1550);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1600);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1650);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1700);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1710);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1750);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1800);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1850);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1900);
INSERT INTO products (title, price) VALUES ('Samsung G22', 1950);
INSERT INTO products (title, price) VALUES ('Samsung G22', 2000);
INSERT INTO products (title, price) VALUES ('Samsung G22', 2010);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 350);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 360);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 370);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 380);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 390);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 400);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 410);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 420);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 430);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 440);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 450);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 460);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 470);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 480);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 490);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 500);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 510);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 520);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 525);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 530);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 535);
INSERT INTO products (title, price) VALUES ('Xiaomi Redmi 8', 540);

--rollback DELETE FROM products;
